language: node_js
node_js:
  - '12'
services:
  - mongodb
cache: yarn
branches:
  only:
    - main
env:
  global:
    - PORT=3000
    - MONGODB_URL=${{ secrets.MONGODB_URL }}
    - JWT_SECRET=${{ secrets.JWT_SECRET }}
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=7
script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
